### ISSUE TITLE
Force RTL only visits sub-documents contained in <browser> elements

### ISSUE THREAD

**Issue by juliandescottes** [mikedeboer/ForceRTL#7]
Firefox devtools are hosted in an iframe, and devtools HTML documents with a dir attribute are not updated when changing the direction with ForceRTL. (Trying to see if devtools should listen to intl.uidirection pref change on their own to update dir attributes or can rely on ForceRTL for this -> https://bugzilla.mozilla.org/show_bug.cgi?id=1305007)

See https://github.com/mikedeboer/ForceRTL/blob/master/lib/forcertl.js#L171-L174

``` javascript
// Walk sub-documents
if (node.localName == "browser") {
  changeChromeDirInDoc(node.contentDocument, dir);
}
```

By doing so the add-on will miss all sub-documents contained in iframes.
We could swap this for

``` javascript
// Walk sub-documents
if (!!node.contentDocument && node.contentDocument != doc) {
  changeChromeDirInDoc(node.contentDocument, dir);
}
```

But maybe the initial implementation is there for a good reason?

**Comment by mikedeboer** [comment]
I'd like you to able to rely on ForceRTL for anything related to proper i18n development. If this change helps, I'll accept the patch right away.
I think it looks good and I don't foresee any regressions.

**Comment by juliandescottes** [comment]
Thanks for the feedback! Sending the PR.
